### ISSUE TITLE
DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19

### ISSUE THREAD

**Issue by rachit1994** [adit-39/openEMO#1]
D:\s\openEMO-master\openEMO-master>python emotion.py

---

angry

---

Enter number of components in the GMMHMM: 32.0
Enter number of mixtures in the Gaussian Model: 32.0

---

fear

---

Enter number of components in the GMMHMM: 32.0
Enter number of mixtures in the Gaussian Model: 32.0

---

happy

---

Enter number of components in the GMMHMM: 32.0
Enter number of mixtures in the Gaussian Model: 32.0

---

sad

---

Enter number of components in the GMMHMM: 32.0
Enter number of mixtures in the Gaussian Model: 32.0

---

surprised

---

Enter number of components in the GMMHMM: 32.0
Enter number of mixtures in the Gaussian Model: 32.0

D:\Python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarnin
g: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0
.19. Reshape your data either using X.reshape(-1, 1) if your data has a single f
eature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
Traceback (most recent call last):
  File "emotion.py", line 89, in <module>
    gmms = create_training_set()
  File "emotion.py", line 84, in create_training_set
    gmms = train_GMMs(emotions, trng_data, GMM_config, pickle_path=pickles + '/g
mmhmm.pkl')
  File "emotion.py", line 60, in train_GMMs
    emo_machines[emo].fit(trng_data[emo])
  File "build\bdist.win32\egg\hmmlearn\base.py", line 420, in fit
  File "D:\Python27\lib\site-packages\sklearn\utils\validation.py", line 393, in
 check_array
    array = array.astype(np.float64)
ValueError: setting an array element with a sequence.

**Comment by adit-39** [comment]
Hi @rachit1994 ,

Since this is code I've written sometime back, the dependencies seem to have changed in terms of what they require as input.

As a quick fix, you can downgrade hmmlearn to the version used when this project was built (0.1.1) from the current version (0.2.x) and also downgrade Cython.

`pip uninstall hmmlearn`
`pip uninstall Cython`
`pip install Cython==0.22`
`pip install hmmlearn==0.1.1`

The above isn't recommended. Ideally, the code would have to be changed to align with the latest release of hmmlearn. If you can do this, please go ahead and make those changes and submit a pull request so others like you who need to use this project can benefit from your code.

**Comment by adit-39** [comment]
Shifted to #2
